[tools]
node = "20.19.4"
"npm:pnpm" = "10.0.0"
go = "1.22.0"

[tasks.service]
description = "Create a new service"
run = "go run ./scripts/tool/cmd gen:service"

[tasks.component]
description = "Create a new React component"
run = "go run ./scripts/tool/cmd gen:component"