name: build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "src/**"
      - "!**/*.test.ts"
      - "!**/*.spec.ts"

env:
  NODE_ENV: 20.19.4
  PNPM_VERSION: 10

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set Node.js version to ${{ env.NODE_ENV }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
